# Generated by Django 5.0.6 on 2024-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ministry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='passcode',
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_category',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('books', 'Books'), ('toys', 'Toys')], max_length=20),
        ),
    ]
