# Generated by Django 5.0.6 on 2024-11-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ministry', '0002_remove_donation_passcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='item_category',
            field=models.CharField(choices=[('child_sponsorship', 'Child Sponsorship'), ('education_fund', 'Education Fund'), ('feeding_program', 'Feeding Program'), ('healthcare_support', 'Healthcare Support'), ('housing_shelter', 'Housing and Shelter'), ('community_outreach', 'Community Outreach'), ('spiritual_growth', 'Spiritual Growth'), ('emergency_relief', 'Emergency Relief'), ('general_support', 'General Support')], max_length=50),
        ),
        migrations.CreateModel(
            name='UploadedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ministry.uploadrequest')),
            ],
        ),
    ]
